"""Generate ``docs/reference/cli.md`` from the package's argparse parser.

The generator imports ``create_parser()`` and walks the resulting
``ArgumentParser`` and its subparsers, rather than scraping ``--help`` output.
Exit codes are recovered by walking the AST of ``main()`` for integer returns,
so the page stays true to the code without a hand-maintained list.

The package name is resolved from ``pyproject.toml`` at runtime. It is
deliberately *not* hard-coded: ``setup.sh`` renames the package when a project
is seeded from this template, and a hard-coded import would break on the first
rename.

Run with ``python tools/docs/gen_cli_reference.py``. CI regenerates and then
runs ``git diff --exit-code`` to catch drift.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import sys
import tomllib
from pathlib import Path

PYPROJECT = Path("pyproject.toml")
OUT_PATH = Path("docs/reference/cli.md")


def package_name() -> str:
    """Resolve the importable package name from ``[project].name``."""
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    return str(data["project"]["name"]).replace("-", "_")


def _subparser_action(
    parser: argparse.ArgumentParser,
) -> argparse._SubParsersAction[argparse.ArgumentParser] | None:
    """Return the parser's subcommand action, if it has one."""
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return action
    return None


def _visible_actions(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    """Return the parser's actions minus help and the subcommand action."""
    return [
        action
        for action in parser._actions  # noqa: SLF001
        if not isinstance(action, argparse._SubParsersAction | argparse._HelpAction)  # noqa: SLF001
    ]


def _value(action: argparse.Action) -> str:
    """Describe the value an action accepts."""
    if action.choices:
        return " \\| ".join(f"`{choice}`" for choice in action.choices)
    if action.nargs == 0:
        return "flag"
    # argparse leaves `type` unset for plain string arguments.
    type_name = getattr(action.type, "__name__", None)
    return f"`{type_name or 'str'}`"


def _default(action: argparse.Action) -> str:
    """Render an action's default value for the table."""
    if action.required or action.default in (None, argparse.SUPPRESS):
        return "—"
    return f"`{action.default}`"


def _rows(actions: list[argparse.Action], *, positional: bool) -> list[str]:
    """Render one table row per action of the requested kind."""
    rows: list[str] = []
    for action in actions:
        if bool(action.option_strings) is positional:
            continue
        name = (
            f"`{action.dest}`"
            if positional
            else ", ".join(f"`{opt}`" for opt in action.option_strings)
        )
        rows.append(
            f"| {name} | {_value(action)} | {_default(action)} | {action.help or '—'} |"
        )
    return rows


def _table(
    heading: str, actions: list[argparse.Action], *, positional: bool
) -> list[str]:
    """Render a titled table, or nothing when there are no matching actions."""
    rows = _rows(actions, positional=positional)
    if not rows:
        return []
    return [
        heading,
        "",
        "| Name | Value | Default | Description |",
        "| --- | --- | --- | --- |",
        *rows,
        "",
    ]


def exit_codes(module_path: Path) -> list[tuple[str, str]]:
    """Recover the exit codes ``main()`` can return by walking its AST."""
    tree = ast.parse(module_path.read_text(encoding="utf-8"))
    codes: set[int] = set()
    for node in ast.walk(tree):
        if not (isinstance(node, ast.FunctionDef) and node.name == "main"):
            continue
        for inner in ast.walk(node):
            if (
                isinstance(inner, ast.Return)
                and isinstance(inner.value, ast.Constant)
                and isinstance(inner.value.value, int)
            ):
                codes.add(inner.value.value)
    described = {
        0: "Success.",
        1: "The command failed, or no command was given.",
        2: "Argument parsing failed (raised by `argparse` itself).",
    }
    codes.add(2)
    return [(str(code), described.get(code, "—")) for code in sorted(codes)]


def render(parser: argparse.ArgumentParser, codes: list[tuple[str, str]]) -> str:
    """Render the CLI reference page."""
    lines = [
        "<!-- Generated by tools/docs/gen_cli_reference.py. Do not edit by hand. -->",
        "",
        "# CLI reference",
        "",
    ]
    if parser.description:
        lines += [parser.description, ""]
    lines += [
        "This page is generated from the argparse parser. Change the parser in",
        "the package's `cli` module, then run `just docs-index`.",
        "",
        f"## `{parser.prog}`",
        "",
    ]
    global_options = _table("**Options**", _visible_actions(parser), positional=False)
    lines += global_options or ["This command takes no options of its own.", ""]

    action = _subparser_action(parser)
    if action is not None:
        lines += [
            "It dispatches to the subcommands below; run one of them.",
            "",
        ]
        for name, subparser in action.choices.items():
            lines += [f"## `{parser.prog} {name}`", ""]
            help_text = next(
                (
                    choice.help
                    for choice in action._choices_actions  # noqa: SLF001
                    if choice.dest == name
                ),
                None,
            )
            if help_text:
                lines += [help_text, ""]
            visible = _visible_actions(subparser)
            lines += _table("**Arguments**", visible, positional=True)
            lines += _table("**Options**", visible, positional=False)

    lines += ["## Exit codes", "", "| Code | Meaning |", "| --- | --- |"]
    lines += [f"| `{code}` | {meaning} |" for code, meaning in codes]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Write the CLI reference page."""
    package = package_name()
    try:
        module = importlib.import_module(f"{package}.cli")
    except ModuleNotFoundError:
        print(f"error: no {package}.cli module to document", file=sys.stderr)
        return 1

    source = Path(str(module.__file__))
    parser = module.create_parser()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(parser, exit_codes(source)), encoding="utf-8")
    print(f"wrote {OUT_PATH} (prog: {parser.prog})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
